from datetime import datetime
from pathlib import Path

from eventbreaker.models.consumer import ConsumerAnalysis
from eventbreaker.models.observation import ObservationResult, ReliabilityFinding
from eventbreaker.scenarios.models import ChaosScenario


def generate(
    consumer_file: Path,
    analysis: ConsumerAnalysis,
    scenarios: list[ChaosScenario],
    result: ObservationResult,
    finding: ReliabilityFinding,
    sandbox: bool,
) -> str:
    """Render a Markdown reliability report and return it as a string."""
    date = datetime.now().strftime("%Y-%m-%d %H:%M")
    exec_mode = "Nebius Sandbox" if sandbox else "local JVM"

    sections: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    sections.append(f"# EventBreaker Reliability Report\n")
    sections.append(f"**File:** `{consumer_file}`  \n**Date:** {date}\n")

    # ── Consumer summary ──────────────────────────────────────────────────────
    sections.append("---\n\n## Consumer\n")
    sections.append(
        f"**Class:** `{analysis.className}.{analysis.methodName}`  \n"
        f"**Event:** `{analysis.eventType}`\n"
    )

    if analysis.dependencies:
        sections.append("\n### Dependencies\n")
        sections.append("| Field | Type |\n|-------|------|\n")
        for dep in analysis.dependencies:
            sections.append(f"| `{dep.name}` | `{dep.type}` |\n")

    if analysis.methodCalls:
        sections.append("\n### Call order\n")
        for i, call in enumerate(analysis.methodCalls, 1):
            sections.append(f"{i}. `{call.expression}`\n")

    # ── Identified risks ──────────────────────────────────────────────────────
    sections.append("\n---\n\n## Identified Risks\n")
    for i, scenario in enumerate(scenarios, 1):
        target = ""
        if scenario.targetDependency:
            target = scenario.targetDependency
            if scenario.targetMethod:
                target += f".{scenario.targetMethod}"
        sections.append(
            f"\n### Risk {i} — {scenario.scenarioType.value}\n"
            f"**Reason:** {scenario.reason}  \n"
            + (f"**Target:** `{target}`  \n" if target else "")
            + f"**Concern:** {scenario.expectedConcern}\n"
        )

    # ── Scenario execution ────────────────────────────────────────────────────
    sections.append(f"\n---\n\n## Scenario Executed: {result.scenario}\n")
    sections.append(f"**Execution mode:** {exec_mode}  \n**Status:** {result.status}\n")

    if result.observations:
        sections.append("\n### Observations\n")
        sections.append("| Dependency.Method | Call Count |\n|-------------------|------------|\n")
        for obs in result.observations:
            flag = " ⚠" if obs.callCount > 1 else ""
            sections.append(f"| `{obs.target}` | {obs.callCount}{flag} |\n")

    # ── Reliability finding ───────────────────────────────────────────────────
    sections.append("\n---\n\n## Reliability Finding\n")
    sections.append(
        f"**Severity:** {finding.severity}  \n"
        f"**Observed:** {finding.summary}\n"
    )
    sections.append(f"\n### Why it matters\n{finding.explanation}\n")
    sections.append(f"\n### Affected method\n`{finding.affectedMethod}`\n")
    sections.append(f"\n### Suggested fix\n{finding.suggestedFix}\n")

    # ── Footer ────────────────────────────────────────────────────────────────
    sections.append(
        "\n---\n\n*Generated by **EventBreaker** — "
        "AI-powered reliability analysis for event-driven consumers.*\n"
    )

    return "".join(sections)


def save(report: str, output_path: Path = Path("eventbreaker-report.md")) -> Path:
    output_path.write_text(report, encoding="utf-8")
    return output_path
